export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const TOGGLE_CHECKBOX = 'TOGGLE_CHECKBOX';

export const SET_DIALOGUE = 'SET_DIALOGUE';

export const SET_PHOTO = 'SET_PHOTO';

export const CLEAR_SIGN_UP_ERROR = 'CLEAR_SIGN_UP_ERROR';

export const LOAD_PHOTO = 'LOAD_PHOTO';
export const LOAD_PHOTO_SUCCESS = 'LOAD_PHOTO_SUCCESS';
export const LOAD_PHOTO_FAILURE = 'LOAD_PHOTO_FAILURE';

export const CHECK_USER_TYPE = 'CHECK_USER_TYPE';
export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS';
export const CHECK_USER_FAILURE= 'CHECK_USER_FAILURE';

export const LOAD_SLIDING_IMAGES= 'LOAD_SLIDING_IMAGES';
export const LOAD_SLIDING_IMAGES_SUCCESS = 'LOAD_SLIDING_IMAGES_SUCCESS';
export const LOAD_SLIDING_IMAGES_FAILURE = 'LOAD_SLIDING_IMAGES_FAILURE';

export const LOAD_RESERVATIONS = 'LOAD_RESERVATIONS';
export const LOAD_RESERVATIONS_SUCCESS = 'LOAD_RESERVATIONS_SUCCESS';
export const LOAD_RESERVATIONS_FAILURE = 'LOAD_RESERVATIONS_FAILURE';

export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_FAILURE = 'LOAD_CATEGORIES_FAILURE';
