export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const TOGGLE_CHECKBOX = 'TOGGLE_CHECKBOX';

export const SET_DIALOGUE = 'SET_DIALOGUE';

export const SET_PHOTO = 'SET_PHOTO';

export const CLEAR_SIGN_UP_ERROR = 'CLEAR_SIGN_UP_ERROR';
export const CLEAR_SIGN_IN_ERROR = 'CLEAR_SIGN_IN_ERROR';

export const LOAD_PHOTO = 'LOAD_PHOTO';
export const LOAD_PHOTO_SUCCESS = 'LOAD_PHOTO_SUCCESS';
export const LOAD_PHOTO_FAILURE = 'LOAD_PHOTO_FAILURE';

export const CHECK_USER_TYPE = 'CHECK_USER_TYPE';
export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS';
export const CHECK_USER_FAILURE= 'CHECK_USER_FAILURE';

export const LOAD_SLIDING_IMAGES= 'LOAD_SLIDING_IMAGES';
export const LOAD_SLIDING_IMAGES_SUCCESS = 'LOAD_SLIDING_IMAGES_SUCCESS';
export const LOAD_SLIDING_IMAGES_FAILURE = 'LOAD_SLIDING_IMAGES_FAILURE';

export const LOAD_RESERVATIONS = 'LOAD_RESERVATIONS';
export const LOAD_RESERVATIONS_SUCCESS = 'LOAD_RESERVATIONS_SUCCESS';
export const LOAD_RESERVATIONS_FAILURE = 'LOAD_RESERVATIONS_FAILURE';

export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_FAILURE = 'LOAD_CATEGORIES_FAILURE';

export const SIGN_OUT_USER = 'SIGN_OUT_USER';

export const SHOW_SIGNUP_LOADER = 'SHOW_SIGNUP_LOADER';
export const HIDE_SIGN_UP_LOADER = 'HIDE_SIGN_UP_LOADER';

export const SHOW_SIGN_IN_LOADER = 'SHOW_SIGN_IN_LOADER';
export const HIDE_SIGN_IN_LOADER = 'HIDE_SIGN_IN_LOADER';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
export const CLEAR_FORGOT_PASSWORD_MESSAGE = 'CLEAR_FORGOT_PASSWORD_MESSAGE';

export const LOAD_SCHEDULED_LESSONS = 'LOAD_SCHEDULED_LESSONS';
export const LOAD_SCHEDULED_LESSONS_SUCCESS = 'LOAD_SCHEDULED_LESSONS_SUCCESS';
export const LOAD_SCHEDULED_LESSONS_FAILURE = 'LOAD_SCHEDULED_LESSONS_FAILURE';

export const LOAD_PENDING_LESSONS = 'LOAD_PENDING_LESSONS';
export const LOAD_PENDING_LESSONS_SUCCESS = 'LOAD_PENDING_LESSONS_SUCCESS';
export const LOAD_PENDING_LESSONS_FAILURE = 'LOAD_PENDING_LESSONS_FAILURE';

export const SET_MENU_VISIBILITY = 'SET_MENU_VISIBILITY';
export const SET_PROFILE_VISIBILITY = 'SET_PROFILE_VISIBILITY';

export const LOAD_FEATURED_INSTRUCTORS = 'LOAD_FEATURED_INSTRUCTORS';
export const LOAD_FEATURED_INSTRUCTORS_SUCCESS = 'LOAD_FEATURED_INSTRUCTORS_SUCCESS';
export const LOAD_FEATURED_INSTRUCTORS_FAILURE = 'LOAD_FEATURED_INSTRUCTORS_FAILURE';

export const LOAD_SEARCH_RESULTS = 'LOAD_SEARCH_RESULTS';
export const LOAD_SEARCH_RESULTS_SUCCESS = 'LOAD_SEARCH_RESULTS_SUCCESS';
export const LOAD_SEARCH_RESULTS_FAILURE = 'LOAD_SEARCH_RESULTS_FAILURE';

export const SET_INSTRUCTOR_FOR_RESERVATION = 'SET_INSTRUCTOR_FOR_RESERVATION';

export const LOAD_AVAILABLE_TIME_SLOTS = 'LOAD_AVAILABLE_TIME_SLOTS';
export const LOAD_AVAILABLE_TIME_SLOTS_SUCCESS = 'LOAD_AVAILABLE_TIME_SLOTS_SUCCESS';
export const LOAD_AVAILABLE_TIME_SLOTS_FAILURE = 'LOAD_AVAILABLE_TIME_SLOTS_FAILURE';
export const SET_SELECTED_SLOT = 'SET_SELECTED_SLOT';
export const RESET_SELECTED_SLOT = 'RESET_SELECTED_SLOT';

export const MAKE_RESERVATION = 'MAKE_RESERVATION';
export const MAKE_RESERVATION_SUCCESS = 'MAKE_RESERVATION_SUCCESS';
export const MAKE_RESERVATION_FAILURE = 'MAKE_RESERVATION_FAILURE';
export const RESET_MAKE_RESERVATION = 'RESET_MAKE_RESERVATION';
