export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const SIGN_UP_USER = 'SIGN_UP_USER';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const TOGGLE_CHECKBOX = 'TOGGLE_CHECKBOX';

export const SET_DIALOGUE = 'SET_DIALOGUE';

export const SET_PHOTO = 'SET_PHOTO';

export const CLEAR_SIGN_UP_ERROR = 'CLEAR_SIGN_UP_ERROR';
export const CLEAR_SIGN_IN_ERROR = 'CLEAR_SIGN_IN_ERROR';

export const LOAD_PHOTO = 'LOAD_PHOTO';
export const LOAD_PHOTO_SUCCESS = 'LOAD_PHOTO_SUCCESS';
export const LOAD_PHOTO_FAILURE = 'LOAD_PHOTO_FAILURE';

export const CHECK_USER_TYPE = 'CHECK_USER_TYPE';
export const CHECK_USER_SUCCESS = 'CHECK_USER_SUCCESS';
export const CHECK_USER_FAILURE= 'CHECK_USER_FAILURE';

export const LOAD_SLIDING_IMAGES= 'LOAD_SLIDING_IMAGES';
export const LOAD_SLIDING_IMAGES_SUCCESS = 'LOAD_SLIDING_IMAGES_SUCCESS';
export const LOAD_SLIDING_IMAGES_FAILURE = 'LOAD_SLIDING_IMAGES_FAILURE';

export const LOAD_RESERVATIONS = 'LOAD_RESERVATIONS';
export const LOAD_RESERVATIONS_SUCCESS = 'LOAD_RESERVATIONS_SUCCESS';
export const LOAD_RESERVATIONS_FAILURE = 'LOAD_RESERVATIONS_FAILURE';

export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_CATEGORIES_FAILURE = 'LOAD_CATEGORIES_FAILURE';

export const SIGN_OUT_USER = 'SIGN_OUT_USER';

export const SHOW_SIGNUP_LOADER = 'SHOW_SIGNUP_LOADER';
export const HIDE_SIGN_UP_LOADER = 'HIDE_SIGN_UP_LOADER';

export const SHOW_SIGN_IN_LOADER = 'SHOW_SIGN_IN_LOADER';
export const HIDE_SIGN_IN_LOADER = 'HIDE_SIGN_IN_LOADER';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE';
export const CLEAR_FORGOT_PASSWORD_MESSAGE = 'CLEAR_FORGOT_PASSWORD_MESSAGE';

export const LOAD_SCHEDULED_LESSONS = 'LOAD_SCHEDULED_LESSONS';
export const LOAD_SCHEDULED_LESSONS_SUCCESS = 'LOAD_SCHEDULED_LESSONS_SUCCESS';
export const LOAD_SCHEDULED_LESSONS_FAILURE = 'LOAD_SCHEDULED_LESSONS_FAILURE';

export const LOAD_PENDING_LESSONS = 'LOAD_PENDING_LESSONS';
export const LOAD_PENDING_LESSONS_SUCCESS = 'LOAD_PENDING_LESSONS_SUCCESS';
export const LOAD_PENDING_LESSONS_FAILURE = 'LOAD_PENDING_LESSONS_FAILURE';

export const SET_MENU_VISIBILITY = 'SET_MENU_VISIBILITY';
export const SET_PROFILE_VISIBILITY = 'SET_PROFILE_VISIBILITY';

export const LOAD_FEATURED_INSTRUCTORS = 'LOAD_FEATURED_INSTRUCTORS';
export const LOAD_FEATURED_INSTRUCTORS_SUCCESS = 'LOAD_FEATURED_INSTRUCTORS_SUCCESS';
export const LOAD_FEATURED_INSTRUCTORS_FAILURE = 'LOAD_FEATURED_INSTRUCTORS_FAILURE';

export const LOAD_SEARCH_RESULTS = 'LOAD_SEARCH_RESULTS';
export const LOAD_SEARCH_RESULTS_SUCCESS = 'LOAD_SEARCH_RESULTS_SUCCESS';
export const LOAD_SEARCH_RESULTS_FAILURE = 'LOAD_SEARCH_RESULTS_FAILURE';
export const CLEAR_SEARCH_DATA = 'CLEAR_SEARCH_DATA';

export const SET_INSTRUCTOR_FOR_RESERVATION = 'SET_INSTRUCTOR_FOR_RESERVATION';

export const LOAD_AVAILABLE_TIME_SLOTS = 'LOAD_AVAILABLE_TIME_SLOTS';
export const LOAD_AVAILABLE_TIME_SLOTS_SUCCESS = 'LOAD_AVAILABLE_TIME_SLOTS_SUCCESS';
export const LOAD_AVAILABLE_TIME_SLOTS_FAILURE = 'LOAD_AVAILABLE_TIME_SLOTS_FAILURE';
export const CLEAR_AVAILABLE_TIME_SLOTS = 'CLEAR_AVAILABLE_TIME_SLOTS';
export const SET_SELECTED_SLOT = 'SET_SELECTED_SLOT';
export const RESET_SELECTED_SLOT = 'RESET_SELECTED_SLOT';
export const LOAD_TIME_SLOTS = 'LOAD_TIME_SLOTS';
export const LOAD_TIME_SLOTS_SUCCESS = 'LOAD_TIME_SLOTS_SUCCESS';
export const LOAD_TIME_SLOTS_FAILURE = 'LOAD_TIME_SLOTS_FAILURE';

export const MAKE_RESERVATION = 'MAKE_RESERVATION';
export const MAKE_RESERVATION_SUCCESS = 'MAKE_RESERVATION_SUCCESS';
export const MAKE_RESERVATION_FAILURE = 'MAKE_RESERVATION_FAILURE';
export const RESET_MAKE_RESERVATION = 'RESET_MAKE_RESERVATION';

export const SET_CONFIRMATION_DIALOGUE = 'SET_CONFIRMATION_DIALOGUE';

export const DECLINE_STUDENT = 'DECLINE_STUDENT';
export const DECLINE_STUDENT_SUCCESS = 'DECLINE_STUDENT_SUCCESS';
export const DECLINE_STUDENT_FAILURE = 'DECLINE_STUDENT_FAILURE';

export const CONFIRM_STUDENT = 'CONFIRM_STUDENT';
export const CONFIRM_STUDENT_SUCCESS = 'CONFIRM_STUDENT_SUCCESS';
export const CONFIRM_STUDENT_FAILURE = 'CONFIRM_STUDENT_FAILURE';

export const LOAD_CURRENT_USER = 'LOAD_CURRENT_USER';
export const LOAD_CURRENT_USER_SUCCESS = 'LOAD_CURRENT_USER_SUCCESS';
export const LOAD_CURRENT_USER_FAILURE = 'LOAD_CURRENT_USER_FAILURE';

export const SET_COST = 'SET_COST';
export const SET_COST_SUCCESS = 'SET_COST_SUCCESS';
export const SET_COST_FAILURE = 'SET_COST_FAILURE';

export const CONFIRM_AVAILABILITY = 'CONFIRM_AVAILABILITY';
export const CONFIRM_AVAILABILITY_SUCCESS = 'CONFIRM_AVAILABILITY_SUCCESS';
export const CONFIRM_AVAILABILITY_FAILURE = 'CONFIRM_AVAILABILITY_FAILURE';

export const LOAD_PENDING_SLOT_DATA = 'LOAD_PENDING_SLOT_DATA';
export const LOAD_PENDING_SLOT_DATA_SUCCESS = 'LOAD_PENDING_SLOT_DATA_SUCCESS';
export const LOAD_PENDING_SLOT_DATA_FAILURE = 'LOAD_PENDING_SLOT_DATA_FAILURE';

export const SET_STUDENT_FOR_DELIVERY = 'SET_STUDENT_FOR_DELIVERY';

export const LDR_RESET = 'LDR_RESET';
export const SET_CALLING = 'SET_CALLING';

export const SHOW_PROFILE_VIEW = 'SHOW_PROFILE_VIEW';

export const USE_APP_STATE = 'USE_APP_STATE';

export const RESET_RELOAD = 'RESET_RELOAD';

export const LOAD_LESSON_CREDIT_URL = 'LOAD_LESSON_CREDIT_URL';
export const LOAD_LESSON_CREDIT_URL_SUCCESS = 'LOAD_LESSON_CREDIT_URL_SUCCESS';
export const LOAD_LESSON_CREDIT_URL_FAILURE = 'LOAD_LESSON_CREDIT_URL_FAILURE';

export const RESET_REDUCERS = 'RESET_REDUCERS';

export const LOAD_TC_TEXT = 'LOAD_TC_TEXT';
export const LOAD_TC_TEXT_SUCCESS = 'LOAD_TC_TEXT_SUCCESS';
export const LOAD_TC_TEXT_FAILURE = 'LOAD_TC_TEXT_FAILURE';
export const RESET_TC_TEXT = 'RESET_TC_TEXT';

export const SHOW_MAIN_LOADER = 'SHOW_MAIN_LOADER';
export const HIDE_MAIN_LOADER = 'HIDE_MAIN_LOADER';

export const DECLINE_INSTRUCTOR= 'DECLINE_INSTRUCTOR';
export const DECLINE_INSTRUCTOR_SUCCESS = 'DECLINE_INSTRUCTOR_SUCCESS';
export const DECLINE_INSTRUCTOR_FAILURE = 'DECLINE_INSTRUCTOR_FAILURE';

export const SET_EMAIL_VERIFICATION = 'SET_EMAIL_VERIFICATION';